import "server-only";
import crypto from "node:crypto";

/**
 * Validates and retrieves the 32-byte AES-256-GCM encryption key from the
 * server-only GOOGLE_ENCRYPTION_SECRET environment variable.
 *
 * Supported formats:
 *   1. 64-character hexadecimal string (e.g. from `openssl rand -hex 32`)
 *   2. Base64-encoded string decoding to 32 bytes
 *   3. 32-character UTF-8 string
 */
function getEncryptionKey(): Buffer {
  const secret = process.env.GOOGLE_ENCRYPTION_SECRET;
  if (!secret) {
    throw new Error(
      "GOOGLE_ENCRYPTION_SECRET environment variable is missing. Set a 32-byte secret to enable Google token encryption."
    );
  }

  // 1. 64-char hex string
  if (/^[0-9a-fA-F]{64}$/.test(secret)) {
    return Buffer.from(secret, "hex");
  }

  // 2. Base64 string decoding to exactly 32 bytes
  try {
    const base64Buf = Buffer.from(secret, "base64");
    if (base64Buf.length === 32 && base64Buf.toString("base64") === secret.trim()) {
      return base64Buf;
    }
  } catch {
    // Not valid base64, fall through to length check
  }

  // 3. Exactly 32-byte string
  const utf8Buf = Buffer.from(secret, "utf-8");
  if (utf8Buf.length === 32) {
    return utf8Buf;
  }

  throw new Error(
    "GOOGLE_ENCRYPTION_SECRET must be exactly 32 bytes (256 bits). Recommended format: 64-character hex string generated via `openssl rand -hex 32`."
  );
}

/**
 * Encrypts a sensitive string (e.g. OAuth access or refresh token) using AES-256-GCM.
 *
 * Each invocation generates a cryptographically secure, unique 12-byte IV and
 * captures the resulting 16-byte authentication tag for tamper detection.
 *
 * @param plaintext The sensitive token or string to encrypt.
 * @returns Serialized string in the format `iv:authTag:ciphertext` (all hex-encoded).
 */
export function encrypt(plaintext: string): string {
  if (!plaintext) {
    throw new Error("Cannot encrypt empty or null payload.");
  }

  const key = getEncryptionKey();
  const iv = crypto.randomBytes(12); // 96-bit IV recommended for AES-GCM
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);

  let encrypted = cipher.update(plaintext, "utf8", "hex");
  encrypted += cipher.final("hex");

  const authTag = cipher.getAuthTag();

  return `${iv.toString("hex")}:${authTag.toString("hex")}:${encrypted}`;
}

/**
 * Decrypts a ciphertext previously generated by `encrypt()`.
 *
 * Verifies the 16-byte authentication tag to detect any tampering before returning
 * the plaintext token. Fails safely without leaking token material.
 *
 * @param encryptedPayload Serialized string in `iv:authTag:ciphertext` hex format.
 * @returns The original plaintext string.
 */
export function decrypt(encryptedPayload: string): string {
  if (!encryptedPayload) {
    throw new Error("Cannot decrypt empty or null payload.");
  }

  const parts = encryptedPayload.split(":");
  if (parts.length !== 3) {
    throw new Error("Invalid encrypted payload format. Expected iv:authTag:ciphertext.");
  }

  const [ivHex, authTagHex, ciphertextHex] = parts;
  if (!ivHex || !authTagHex || !ciphertextHex) {
    throw new Error("Invalid encrypted payload: one or more components are empty.");
  }

  const iv = Buffer.from(ivHex, "hex");
  const authTag = Buffer.from(authTagHex, "hex");

  if (iv.length !== 12) {
    throw new Error("Invalid IV length. Expected 12 bytes for AES-256-GCM.");
  }

  if (authTag.length !== 16) {
    throw new Error("Invalid authentication tag length. Expected 16 bytes.");
  }

  const key = getEncryptionKey();
  const decipher = crypto.createDecipheriv("aes-256-gcm", key, iv);
  decipher.setAuthTag(authTag);

  try {
    let decrypted = decipher.update(ciphertextHex, "hex", "utf8");
    decrypted += decipher.final("utf8");
    return decrypted;
  } catch {
    throw new Error("Decryption failed: authentication tag mismatch or corrupted ciphertext.");
  }
}
